### ISSUE TITLE
XAMPP + win 10 

### ISSUE THREAD

**Issue by Gbislay** [alexis-luna/codeigniter4-auth-and-user-management#7]
Hi.
Tring to run this on Win 10 using XXAMP . Checked sys requirements and db but  http://localhost/users/public/ ... returns this ....

Deprecated: Required parameter $userAgent follows optional parameter $body in C:\xampp\htdocs\users\system\HTTP\IncomingRequest.php on line 161

Fatal error: Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\users\app\Config\Events.php:33) in C:\xampp\htdocs\users\system\Debug\Exceptions.php:164 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 164) #1 C:\xampp\htdocs\users\system\Debug\Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500) #2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException)) #3 {main} thrown in C:\xampp\htdocs\users\system\Debug\Exceptions.php on line 164

Fatal error: Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\users\app\Config\Events.php:33) in C:\xampp\htdocs\users\system\Debug\Exceptions.php:164 Stack trace: #0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 164) #1 C:\xampp\htdocs\users\system\Debug\Exceptions.php(164): header('HTTP/1.1 500 In...', true, 500) #2 C:\xampp\htdocs\users\system\Debug\Exceptions.php(224): CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException)) #3 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler() #4 {main} thrown in C:\xampp\htdocs\users\system\Debug\Exceptions.php on line 164

**Comment by treborin** [comment]
PHP version?
CI4 version?

**Comment by Gbislay** [comment]
php  8.0.15 
@package    CodeIgniter
 * @author     CodeIgniter Dev Team
 * @copyright  2019-2020 CodeIgniter Foundation
 * @license    https://opensource.org/licenses/MIT	MIT License
 * @link       https://codeigniter.com
 * @since      Version 4.0.0
 * @filesource

**Comment by treborin** [comment]
Just my suggestion:
- As Version 4.0.0 is for PHP 7.4, please install (not update) to latest CI4 Version 4.2.4 here: [https://github.com/codeigniter4/CodeIgniter4](url)
- If you need to deal with users management in CI4, you could try to use Shield, from the CI4 Team here: [https://github.com/codeigniter4/shield](url)
- Another option is this nice and new admin panel starter (i like it very much): [https://github.com/gheav/CI4-StarterPanel](url)

**Comment by Gbislay** [comment]
thanks, treborin. I'll have a look at both suggestions
